config/routes.rb
Brslam::Application.routes.draw do
  resources :urls, :only => [:show, :new, :create]

  root :to => redirect('/urls/new')

end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :url, :presence => true

  # Create a short code string
  def short_code
    id.to_s 36
  end

  # Take number from base 36 value to get ID
  def self.find_using_short_code!(short_code)
    find short_code.to_i(36)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @shortened_url = Url.new
  end

  def create
    @shortened_url = Url.new(params[:url])
    if @shortened_url.save
      flash[:shortened_id] = @shortened_url.id
      redirect_to new_url_url
    else
      render :action => 'new'
    end
  end

  def show
    @shortened_url = Url.find(params[:id])
    redirect_to @shortened_url.url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>brsl.am</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application', 'brslam' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:shortened_id].present? %>
  <p class="short-link">
    The shortened URL is available <%= link_to 'here', url_url(flash[:shortened_id]) %>. (Right click to copy).
  </p>
<% end %>

<%= yield %>

</body>
</html>

app/views/urls/new.html.erb
<h1>Shorten your URL</h1>

<%= form_for @shortened_url do |form| %>
  <p>
    <%= form.label :url, 'Your link:' %>
    <%= form.text_field :url %>
  </p>

  <% if @shortened_url.errors[:url].any? %>
    <p class='error-messages'>
      The URL <%= @shortened_url.errors[:url].to_sentence %>.
    </p>
  <% end %>

  <p class='buttons'>
    <%= form.submit 'Shorten URL' %>
  </p>
<% end %>

<iframe id='preview-url' style='width: 600px; height: 400px; display: none;'></iframe>